### ISSUE TITLE
Return/Enter should not open a directory for editing

### ISSUE THREAD

**Issue by Skeeve** [sxyazi/yazi#3357]
### `yazi --debug` output

```Shell
Yazi
    Version: 25.5.31 (Homebrew 2025-05-30)
    Debug  : false
    Triple : aarch64-apple-darwin (macos-aarch64)
    Rustc  : 1.87.0 (17067e9a 2025-05-09)

Ya
    Version: 25.5.31 (Homebrew 2025-05-30)

Emulator
    TERM                : Some("xterm-256color")
    TERM_PROGRAM        : Some("iTerm.app")
    TERM_PROGRAM_VERSION: Some("3.6.5")
    Brand.from_env      : Some(Iterm2)
    Emulator.detect     : Emulator { kind: Left(Iterm2), light: true, csi_16t: (0, 0), force_16t: false }

Adapter
    Adapter.matches    : Iip
    Dimension.available: Dimension { rows: 25, columns: 80, width: 1120, height: 700 }

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : Some("/bin/zsh")
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(OpenerRule { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for: None, spread: true })
    block-create: Some(OpenerRule { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for: None, spread: true })
    block-rename: Some(OpenerRule { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file          : 5.41
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: No such file or directory (os error 2) / No such file or directory (os error 2)
    pdftoppm      : No such file or directory (os error 2)
    magick        : No such file or directory (os error 2)
    fzf           : 0.67.0
    fd/fdfind     : No such file or directory (os error 2) / No such file or directory (os error 2)
    rg            : No such file or directory (os error 2)
    chafa         : No such file or directory (os error 2)
    zoxide        : 0.9.7
    7zz/7z        : 25.01 / No such file or directory (os error 2)
    resvg         : No such file or directory (os error 2)
    jq            : 1.7.1

Clipboard
    wl-copy/paste: No such file or directory (os error 2) / No such file or directory (os error 2)
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)

Routine
    `file -bL --mime-type`: text/plain
```

### Please describe the problem you're trying to solve

I have the bad habbit of pressing Enter instead of coursor right and so the directory is opened in vim and I have to leave it with :q

I do not think that it's a good idea to open a directory in vim, but I may be mistaken.

### Would you be willing to contribute this feature?

- [x] Yes, I'll give it a shot

### Describe the solution you'd like

When pressing enter on a directory something else should happen instead of opening the editot.

For example one of these:

- nothing
- Directory renaming
- cd into the directory
- 

### Checklist

- [x] I have searched the existing issues/discussions
- [x] The [latest nightly build](https://yazi-rs.github.io/docs/installation/#binaries) doesn't already have this feature

**Comment by tnaseem** [comment]
You can modify the keybinding in your `keymap.toml` file. This is what I did, as I have the same habit!

In my case, I prepend the keymap (which takes higher priority) and use <Enter> to enter the directory instead. See below:

```
[mgr]

prepend_keymap = [
  { on = "<Enter>", run = "enter", desc = "Enter child directory" },
]
```

Hope this helps.

**Comment by sxyazi** [comment]
This is by design - Yazi allows users to open a directory in an external program, see https://yazi-rs.github.io/docs/faq#why-separate-open-enter

- If `Enter` were changed to the [`noop`](https://yazi-rs.github.io/docs/configuration/keymap#mgr.noop) command, it would lose the ability to open files or directories
- If `Enter` were changed to [`rename`](https://yazi-rs.github.io/docs/configuration/keymap#mgr.rename) it would duplicate the `r` key's function
- If changed to [`enter`](https://yazi-rs.github.io/docs/configuration/keymap#mgr.enter) it would overlap with `l` and the right-arrow key

So there are no plans to change this behavior. However, I might be able to find a way to make it easier for users to override the directory-open behavior to do nothing.

**Comment by sxyazi** [comment]
You can add the following to your `yazi.toml`:

```toml
[[open.prepend_rules]]
url = "*/"
use = []
```

to disable the [preset open rule for directories](https://github.com/sxyazi/yazi/blob/765cc0dce55a6f6e1acead43a0684663a544aadc/yazi-config/preset/yazi-default.toml#L68-L69).

Note that the release version has a bug that prevents this from working - when a user specifies a higher-priority open rule via `prepend_rules`, the preset open rules are still matched and applied. I have fixed it in https://github.com/sxyazi/yazi/pull/3360.

**Comment by Skeeve** [comment]
> Note that the release version has a bug that prevents this from working - when a user specifies a higher-priority open rule via `prepend_rules`, the preset open rules are still matched and applied. I have fixed it in [#3360](https://github.com/sxyazi/yazi/pull/3360).

~~As I do not have any user specific rule in place, I'm wondering why this does not work at all. Neither in my homebrew-installed version nor in the nightly build from last week I still have lying around.~~

**Update:** Works in the current nightly build!

@tnaseem: That, unfortunately, takes away the possibility to open a file in my editor by pressing enter.

**Comment by Skeeve** [comment]
Thanks for you help, @sxyazi, but I still have another question.

In keymap I can define what to "run" when a key is pressed. There is no way to define what to run, depending on the selected item.

So with the settings you gave me, `<Enter>` will run "open" and open then can, based on the entry, decide what to do. Unfortunately entering a directory is nothing that "open" can do. This can only be done by "run" in the keymap.

It would be good, "open" could do an "enter" or keymap could have rules based on the file type or name.

**Comment by sxyazi** [comment]
I believe https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi is
exactly what you're looking which is also mentioned in that FAQ

**Comment by Skeeve** [comment]
Thanks a thousand times @sxyazi I'm sorry I missed that plugin in the FAQ. Now yazi on my M4 Mac works like a charm. Only on my Imtel Mac it's a bit picky as ya cannot install flavors. But that's another issue I already opened.
